### PR TITLE
Potatoboard speedrun

### PR DESCRIPTION
**Pull request by rgantzos**
### Resolves

An ongoing need for speedy potatoes.

### Changes

This creates a new database for the fastest time, along with detecting if the new message hitting the potatoboard is faster than ever before. It it is, then it sends an alert to the server news channel.

### CODE REVIEW

**Comment by jaxonbaxon** [comment]
this would be awesome, but potatoboard isn't supposed to be competitive since it's like starboard. it's for posts people find funny or should be mentioned more, and i feel like adding a speedrun element might make potatoboard a bit bland at times.

**Comment by rgantzos** [comment]
> this would be awesome, but potatoboard isn't supposed to be competitive since it's like starboard. it's for posts people find funny or should be mentioned more, and i feel (personally) like adding a speedrun element might make potatoboard a bit bland at times.

IMO, it would only encourage people to get more creative and let their charisma show as well as possible. If it’s ideal for all messages on the potatoboard to be great, that would still cause it to be bland. It also adds some friendly competition to make sure people are active, since I expect the record would be pretty fast.

**Comment by jaxonbaxon** [comment]
> > ...
> 
> IMO, it would only encourage people to get more creative and let their charisma show as well as possible. If it’s ideal for all messages on the potatoboard to be great, that would still cause it to be bland. It also adds some friendly competition to make sure people are active, since I expect the record would be pretty fast.

i do get where you're coming from, but competition might break the potato economy (if you know what i mean) potatos for potatoboard should really only be given imo to posts that DESERVE the potatoes, and not the ones that just want to speedrun and get their name plastered on the channel.

**Comment by jaxonbaxon** [comment]
i would change "...before. Only..." to "...before in only..." when scradd is sending the post to potatoboard channel

**Comment by Hans5958** [comment]
Why there are ideas for gamify even a mundane thing as a starboard

**Comment by RedGuy12** [comment]
i decide i agree with jaxon

**Pull request closed without merging**
