### PR TITLE
don't break when badWords arrays are empty

### LINKED ISSUE #281: Empty arrays in `badWords.ts` cause problems
Having empty arrays in `badWords.ts` causes a scenario where scradd recursively warns itself (and other people) for bad words. `/is-bad-word text: a` claims that it would give you 6 strikes. One can of course add a regex to each array in `badWords.ts` but you then need to make sure that you don't commit it and that you copy it over to every branch you make... not ideal.
Possible solutions:
- fix the bug (not sure how but I might take a look)
- gitignore `badWords.ts` and hope that you never need to change the seleton version in this repo

### PR DESCRIPTION
**Pull request by pufferfish101007**
resolves #281
`/(^.^)/` will never match anything (and also makes a cute face), as opposed to `/()/`.

### CODE REVIEW

**Comment by pufferfish101007** [comment]
gah can package-lock.json be gitignored please

**Comment by RedGuy12** [comment]
oh thanks



> gah can package-lock.json be gitignored please

https://github.com/scratchaddons-community/scradd/commit/51f12911e2d1f7b9b48d943348e297bb110ceff0 should fix the conflicts

**Comment by pufferfish101007** [comment]
> oh thanks
> 
> > gah can package-lock.json be gitignored please
> 
> [51f1291](https://github.com/scratchaddons-community/scradd/commit/51f12911e2d1f7b9b48d943348e297bb110ceff0) should fix the conflicts

it'll fix it for the future, yes
unfortunately this branch is behind main for dependencies... i'll resolve the conflicts now

**Comment by pufferfish101007** [comment]
conflicts resolved

**Pull request merged**
