### PR TITLE
Added poll command

### LINKED ISSUE #166: /poll

### PR DESCRIPTION
**Pull request by TheAnvils**
### Resolves

Resolves #166 

### Changes

Poll command
-   
To contribute 
### Tests

Yes by running the code
### Agree to our policies

-   [yes ] I agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/main/.github/CODE_OF_CONDUCT.md).
-   [ yes] I agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/main/.github/CONTRIBUTING.md).

### TODO
Review the code and make some changes 
-   [ ]

### CODE REVIEW

**Comment by TheAnvils** [comment]
That will be added in the future

**Comment by retronbv** [comment]
~~how about now~~

**Comment by TheAnvils** [comment]
Ok fine but it will take a while

**Comment by TheAnvils** [comment]
I encountered an error while testing the new one, I will rewrite it in typescript to hopefully fix it and open another pull request once it's finished.

**Comment by Aid0nModder** [comment]
It would be nice if it wasn't so static, for example the embed could show the total number of votes and the votes for each option.
For example my bots poll command has a custom function to draw a progress bar which i use to show the ratio of votes.
unknown

Although right now multiple custom options should be a focal point, a poll command with 2 options is less desirable...

**Comment by TheAnvils** [comment]
Custom options have been added (custom emojis to be exact). The votes thing is a good idea, I'll make something like that

**Comment by RedGuy12** [comment]
FYI @TheAnvils, a `makeProgressBar` utility function already exists in `/lib/numbers.ts` that you can import. It takes a decimal and returns a string.

**Comment by TheAnvils** [comment]
Ok ty, the custom emojis broke the entire commands so yeah I'm gonna rewrite it after school tomorrow

**Comment by TheAnvils** [comment]
I mean command smh

**Pull request closed without merging**
