### PR TITLE
it's just.. not funny

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**

### CODE REVIEW

**Comment by YandeMC** [comment]
its very funny

**Comment by RedGuy12** [comment]
if you want it to be removed, please provide ideas for a message i could replace it with

**Comment by rgantzos** [comment]
`**${member.user.displayName}** got banned.`

**Comment by RedGuy12** [comment]
that's not funnier either lmao

**Comment by GrahamSH-LLK** [comment]
**${member.user.displayName}** got scratched off the server or smth

**Comment by Platformer444** [comment]
ERROR 404: User **${member.user.username}** wasn't found in the server

**Comment by rgantzos** [comment]
`I need help hiding **${member.user.displayName}**'s body, I've made a terrible mistake.`

**Comment by YandeMC** [comment]
> `I need help hiding **${member.user.displayName}**'s body, I've made a terrible mistake.`

WHAT IM ADDING THAT TO SCRADDETTE

**Pull request merged**
